/* eslint-disable */
import * as types from "./graphql";
import { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
  "\n  mutation userSignUp($input: UserSignUpInput!) {\n    userSignUp(input: $input) {\n      user {\n        id\n        name\n      }\n    }\n  }\n":
    types.UserSignUpDocument,
  "\n  mutation ParticipationImageBulkUpdate($input: ParticipationImageBulkUpdateInput!, $permission: CheckIsSelfPermissionInput!) {\n    participationImageBulkUpdate(input: $input, permission: $permission) {\n      ... on ParticipationImageBulkUpdateSuccess {\n        participation {\n          id\n          images\n        }\n      }\n    }\n  }\n":
    types.ParticipationImageBulkUpdateDocument,
  "\n  mutation CreateReservation($input: ReservationCreateInput!) {\n    reservationCreate(input: $input) {\n      ... on ReservationCreateSuccess {\n        reservation {\n          id\n          status\n        }\n      }\n    }\n  }\n":
    types.CreateReservationDocument,
  '\n  query GetArticle($id: ID!, $permission: CheckCommunityPermissionInput!) {\n    article(id: $id, permission: $permission) {\n      id\n      title\n      introduction\n      body\n      category\n      thumbnail\n      publishedAt\n      createdAt\n      updatedAt\n      authors {\n        id\n        name\n        image\n        bio\n      }\n      relatedUsers {\n        id\n        name\n        image\n        bio\n      }\n    }\n\n    articles(\n      first: 4,\n      filter: {\n        categories: ["INTERVIEW"],\n        publishStatus: [PUBLIC]\n      },\n      sort: { publishedAt: desc }\n    ) {\n      edges {\n        node {\n          id\n          title\n          introduction\n          thumbnail\n          publishedAt\n          authors {\n            id\n            name\n            image\n          }\n        }\n      }\n    }\n  }\n':
    types.GetArticleDocument,
  "\n  query GetArticles($first: Int, $cursor: String, $filter: ArticleFilterInput, $sort: ArticleSortInput) {\n    articles(first: $first, cursor: $cursor, filter: $filter, sort: $sort) {\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      edges {\n        node {\n          id\n          title\n          introduction\n          thumbnail\n          publishedAt\n          authors {\n            id\n            name\n            image\n          }\n        }\n      }\n    }\n  }\n":
    types.GetArticlesDocument,
  "\n  query currentUser {\n    currentUser {\n      user {\n        id\n        name\n      }\n    }\n  }\n":
    types.CurrentUserDocument,
  "\n  fragment OpportunityFields on Opportunity {\n    id\n    title\n    description\n    image\n    community {\n      id\n    }\n    place {\n      id\n      name\n      address\n      city {\n        name\n        state {\n          name\n        }\n      }\n    }\n    slots {\n      edges {\n        node {\n          id\n          startsAt\n          endsAt\n          capacity\n        }\n      }\n    }\n    feeRequired\n    pointsToEarn\n  }\n":
    types.OpportunityFieldsFragmentDoc,
  "\n  query GetOpportunities(\n    $upcomingFilter: OpportunityFilterInput\n    $featuredFilter: OpportunityFilterInput\n    $allFilter: OpportunityFilterInput\n    $similarFilter: OpportunityFilterInput\n    $first: Int\n    $cursor: String\n  ) {\n    upcoming: opportunities(\n      filter: $upcomingFilter\n      sort: { createdAt: desc }\n      first: 5\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n    \n    featured: opportunities(\n      filter: $featuredFilter\n      first: 5\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n    \n    similar: opportunities(\n      filter: $similarFilter\n      first: 3\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n    \n    all: opportunities(\n      filter: $allFilter\n      first: $first\n      cursor: $cursor\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n  \n":
    types.GetOpportunitiesDocument,
  '\n  query GetOpportunity($id: ID!, $permission: CheckCommunityPermissionInput!) {\n    opportunity(id: $id, permission: $permission) {\n      id\n      title\n      description\n      body\n      category\n      capacity\n      pointsToEarn\n      feeRequired\n      requireApproval\n      publishStatus\n      image\n      files\n      createdAt\n      updatedAt\n      community {\n        id\n        name\n        image\n      }\n      createdByUser {\n        id\n        name\n        image\n        articlesAboutMe(\n          first: 1,\n          filter: { publishStatus: [PUBLIC], categories: ["INTERVIEW"] },\n          sort: { publishedAt: desc }\n        ) {\n          edges {\n            node {\n              id\n              title\n              introduction\n              thumbnail\n              createdAt\n            }\n          }\n        }\n        opportunitiesCreatedByMe(first: 5) {\n          edges {\n            node {\n              id\n              title\n              description\n              category\n              capacity\n              community {\n                id\n                name\n                image\n              }\n              pointsToEarn\n              feeRequired\n              requireApproval\n              publishStatus\n              image\n              createdAt\n              updatedAt\n              slots {\n                edges {\n                  node {\n                    id\n                    startsAt\n                    endsAt\n                    participations {\n                      edges {\n                        node {\n                          id\n                          status\n                          user {\n                            id\n                            name\n                            image\n                          }\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      place {\n        id\n        name\n        address\n        latitude\n        longitude\n        city {\n          name\n          state {\n            name\n          }\n        }\n      }\n      slots {\n        edges {\n          node {\n            id\n            startsAt\n            endsAt\n            participations {\n              edges {\n                node {\n                  id\n                  status\n                  images\n                  user {\n                    id\n                    name\n                    image\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n':
    types.GetOpportunityDocument,
  "\n  query GetParticipation($id: ID!) {\n    participation(id: $id) {\n      id\n      images\n      reason\n      reservation {\n        id\n        opportunitySlot {\n          id\n          capacity\n          startsAt\n          endsAt\n          hostingStatus\n          opportunity {\n            id\n            title\n            description\n            body\n            category\n            capacity\n            pointsToEarn\n            feeRequired\n            requireApproval\n            publishStatus\n            image\n            files\n            createdAt\n            updatedAt\n            community {\n              id\n              name\n              image\n            }\n            createdByUser {\n              id\n              name\n              image\n            }\n            place {\n              id\n              name\n              address\n              latitude\n              longitude\n              city {\n                name\n                state {\n                  name\n                }\n              }\n            }\n            slots {\n              edges {\n                node {\n                  id\n                  startsAt\n                  endsAt\n                  participations {\n                    edges {\n                      node {\n                        id\n                        status\n                        images\n                        user {\n                          id\n                          name\n                          image\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n        participations {\n          id\n          user {\n            id\n            name\n            image\n          }\n        }\n      }\n      source\n      status\n      statusHistories {\n        edges {\n          node {\n            id\n            status\n            reason\n            createdAt\n            createdByUser {\n              id\n              name\n            }\n          }\n        }\n      }\n      updatedAt\n      user {\n        id\n        name\n        image\n      }\n    }\n  }\n":
    types.GetParticipationDocument,
  "\n  query SearchOpportunities(\n    $filter: OpportunityFilterInput\n    $first: Int\n  ) {\n    opportunities(\n      filter: $filter\n      first: $first\n    ) {\n      edges {\n        node {\n          id\n          title\n          description\n          category\n          capacity\n          community {\n            id\n            name\n            image\n          }\n          pointsToEarn\n          feeRequired\n          requireApproval\n          publishStatus\n          image\n          createdAt\n          updatedAt\n          place {\n            id\n            name\n            address\n            latitude\n            longitude\n            city {\n              name\n              state {\n                name\n              }\n            }\n          }\n          slots {\n            edges {\n              node {\n                id\n                startsAt\n                endsAt\n                capacity\n                participations {\n                  edges {\n                    node {\n                      id\n                      status\n                      user {\n                        id\n                        name\n                        image\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n":
    types.SearchOpportunitiesDocument,
  "\n  query GetUserWithDetailsAndPortfolios(\n    $id: ID!,\n    $first: Int,\n    $after: String,\n    $filter: PortfolioFilterInput,\n    $sort: PortfolioSortInput\n  ) {\n    user(id: $id) {\n      id\n      name\n      image\n      bio\n      sysRole\n      currentPrefecture\n      urlFacebook\n      urlInstagram\n      urlWebsite\n      urlX\n      urlYoutube\n      portfolios(\n        first: $first,\n        cursor: $after,\n        filter: $filter,\n        sort: $sort\n      ) {\n        edges {\n          node {\n            id\n            title\n            category\n            date\n            thumbnailUrl\n            source\n            place {\n              id\n              name\n            }\n            participants {\n              id\n              name\n              image\n            }\n          }\n          cursor\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n":
    types.GetUserWithDetailsAndPortfoliosDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  mutation userSignUp($input: UserSignUpInput!) {\n    userSignUp(input: $input) {\n      user {\n        id\n        name\n      }\n    }\n  }\n",
): (typeof documents)["\n  mutation userSignUp($input: UserSignUpInput!) {\n    userSignUp(input: $input) {\n      user {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  mutation ParticipationImageBulkUpdate($input: ParticipationImageBulkUpdateInput!, $permission: CheckIsSelfPermissionInput!) {\n    participationImageBulkUpdate(input: $input, permission: $permission) {\n      ... on ParticipationImageBulkUpdateSuccess {\n        participation {\n          id\n          images\n        }\n      }\n    }\n  }\n",
): (typeof documents)["\n  mutation ParticipationImageBulkUpdate($input: ParticipationImageBulkUpdateInput!, $permission: CheckIsSelfPermissionInput!) {\n    participationImageBulkUpdate(input: $input, permission: $permission) {\n      ... on ParticipationImageBulkUpdateSuccess {\n        participation {\n          id\n          images\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  mutation CreateReservation($input: ReservationCreateInput!) {\n    reservationCreate(input: $input) {\n      ... on ReservationCreateSuccess {\n        reservation {\n          id\n          status\n        }\n      }\n    }\n  }\n",
): (typeof documents)["\n  mutation CreateReservation($input: ReservationCreateInput!) {\n    reservationCreate(input: $input) {\n      ... on ReservationCreateSuccess {\n        reservation {\n          id\n          status\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetArticle($id: ID!, $permission: CheckCommunityPermissionInput!) {\n    article(id: $id, permission: $permission) {\n      id\n      title\n      introduction\n      body\n      category\n      thumbnail\n      publishedAt\n      createdAt\n      updatedAt\n      authors {\n        id\n        name\n        image\n        bio\n      }\n      relatedUsers {\n        id\n        name\n        image\n        bio\n      }\n    }\n\n    articles(\n      first: 4,\n      filter: {\n        categories: ["INTERVIEW"],\n        publishStatus: [PUBLIC]\n      },\n      sort: { publishedAt: desc }\n    ) {\n      edges {\n        node {\n          id\n          title\n          introduction\n          thumbnail\n          publishedAt\n          authors {\n            id\n            name\n            image\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query GetArticle($id: ID!, $permission: CheckCommunityPermissionInput!) {\n    article(id: $id, permission: $permission) {\n      id\n      title\n      introduction\n      body\n      category\n      thumbnail\n      publishedAt\n      createdAt\n      updatedAt\n      authors {\n        id\n        name\n        image\n        bio\n      }\n      relatedUsers {\n        id\n        name\n        image\n        bio\n      }\n    }\n\n    articles(\n      first: 4,\n      filter: {\n        categories: ["INTERVIEW"],\n        publishStatus: [PUBLIC]\n      },\n      sort: { publishedAt: desc }\n    ) {\n      edges {\n        node {\n          id\n          title\n          introduction\n          thumbnail\n          publishedAt\n          authors {\n            id\n            name\n            image\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query GetArticles($first: Int, $cursor: String, $filter: ArticleFilterInput, $sort: ArticleSortInput) {\n    articles(first: $first, cursor: $cursor, filter: $filter, sort: $sort) {\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      edges {\n        node {\n          id\n          title\n          introduction\n          thumbnail\n          publishedAt\n          authors {\n            id\n            name\n            image\n          }\n        }\n      }\n    }\n  }\n",
): (typeof documents)["\n  query GetArticles($first: Int, $cursor: String, $filter: ArticleFilterInput, $sort: ArticleSortInput) {\n    articles(first: $first, cursor: $cursor, filter: $filter, sort: $sort) {\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      edges {\n        node {\n          id\n          title\n          introduction\n          thumbnail\n          publishedAt\n          authors {\n            id\n            name\n            image\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query currentUser {\n    currentUser {\n      user {\n        id\n        name\n      }\n    }\n  }\n",
): (typeof documents)["\n  query currentUser {\n    currentUser {\n      user {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  fragment OpportunityFields on Opportunity {\n    id\n    title\n    description\n    image\n    community {\n      id\n    }\n    place {\n      id\n      name\n      address\n      city {\n        name\n        state {\n          name\n        }\n      }\n    }\n    slots {\n      edges {\n        node {\n          id\n          startsAt\n          endsAt\n          capacity\n        }\n      }\n    }\n    feeRequired\n    pointsToEarn\n  }\n",
): (typeof documents)["\n  fragment OpportunityFields on Opportunity {\n    id\n    title\n    description\n    image\n    community {\n      id\n    }\n    place {\n      id\n      name\n      address\n      city {\n        name\n        state {\n          name\n        }\n      }\n    }\n    slots {\n      edges {\n        node {\n          id\n          startsAt\n          endsAt\n          capacity\n        }\n      }\n    }\n    feeRequired\n    pointsToEarn\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query GetOpportunities(\n    $upcomingFilter: OpportunityFilterInput\n    $featuredFilter: OpportunityFilterInput\n    $allFilter: OpportunityFilterInput\n    $similarFilter: OpportunityFilterInput\n    $first: Int\n    $cursor: String\n  ) {\n    upcoming: opportunities(\n      filter: $upcomingFilter\n      sort: { createdAt: desc }\n      first: 5\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n    \n    featured: opportunities(\n      filter: $featuredFilter\n      first: 5\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n    \n    similar: opportunities(\n      filter: $similarFilter\n      first: 3\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n    \n    all: opportunities(\n      filter: $allFilter\n      first: $first\n      cursor: $cursor\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n  \n",
): (typeof documents)["\n  query GetOpportunities(\n    $upcomingFilter: OpportunityFilterInput\n    $featuredFilter: OpportunityFilterInput\n    $allFilter: OpportunityFilterInput\n    $similarFilter: OpportunityFilterInput\n    $first: Int\n    $cursor: String\n  ) {\n    upcoming: opportunities(\n      filter: $upcomingFilter\n      sort: { createdAt: desc }\n      first: 5\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n    \n    featured: opportunities(\n      filter: $featuredFilter\n      first: 5\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n    \n    similar: opportunities(\n      filter: $similarFilter\n      first: 3\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n    \n    all: opportunities(\n      filter: $allFilter\n      first: $first\n      cursor: $cursor\n    ) {\n      edges {\n        node {\n          ...OpportunityFields\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n  \n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetOpportunity($id: ID!, $permission: CheckCommunityPermissionInput!) {\n    opportunity(id: $id, permission: $permission) {\n      id\n      title\n      description\n      body\n      category\n      capacity\n      pointsToEarn\n      feeRequired\n      requireApproval\n      publishStatus\n      image\n      files\n      createdAt\n      updatedAt\n      community {\n        id\n        name\n        image\n      }\n      createdByUser {\n        id\n        name\n        image\n        articlesAboutMe(\n          first: 1,\n          filter: { publishStatus: [PUBLIC], categories: ["INTERVIEW"] },\n          sort: { publishedAt: desc }\n        ) {\n          edges {\n            node {\n              id\n              title\n              introduction\n              thumbnail\n              createdAt\n            }\n          }\n        }\n        opportunitiesCreatedByMe(first: 5) {\n          edges {\n            node {\n              id\n              title\n              description\n              category\n              capacity\n              community {\n                id\n                name\n                image\n              }\n              pointsToEarn\n              feeRequired\n              requireApproval\n              publishStatus\n              image\n              createdAt\n              updatedAt\n              slots {\n                edges {\n                  node {\n                    id\n                    startsAt\n                    endsAt\n                    participations {\n                      edges {\n                        node {\n                          id\n                          status\n                          user {\n                            id\n                            name\n                            image\n                          }\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      place {\n        id\n        name\n        address\n        latitude\n        longitude\n        city {\n          name\n          state {\n            name\n          }\n        }\n      }\n      slots {\n        edges {\n          node {\n            id\n            startsAt\n            endsAt\n            participations {\n              edges {\n                node {\n                  id\n                  status\n                  images\n                  user {\n                    id\n                    name\n                    image\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n',
): (typeof documents)['\n  query GetOpportunity($id: ID!, $permission: CheckCommunityPermissionInput!) {\n    opportunity(id: $id, permission: $permission) {\n      id\n      title\n      description\n      body\n      category\n      capacity\n      pointsToEarn\n      feeRequired\n      requireApproval\n      publishStatus\n      image\n      files\n      createdAt\n      updatedAt\n      community {\n        id\n        name\n        image\n      }\n      createdByUser {\n        id\n        name\n        image\n        articlesAboutMe(\n          first: 1,\n          filter: { publishStatus: [PUBLIC], categories: ["INTERVIEW"] },\n          sort: { publishedAt: desc }\n        ) {\n          edges {\n            node {\n              id\n              title\n              introduction\n              thumbnail\n              createdAt\n            }\n          }\n        }\n        opportunitiesCreatedByMe(first: 5) {\n          edges {\n            node {\n              id\n              title\n              description\n              category\n              capacity\n              community {\n                id\n                name\n                image\n              }\n              pointsToEarn\n              feeRequired\n              requireApproval\n              publishStatus\n              image\n              createdAt\n              updatedAt\n              slots {\n                edges {\n                  node {\n                    id\n                    startsAt\n                    endsAt\n                    participations {\n                      edges {\n                        node {\n                          id\n                          status\n                          user {\n                            id\n                            name\n                            image\n                          }\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      place {\n        id\n        name\n        address\n        latitude\n        longitude\n        city {\n          name\n          state {\n            name\n          }\n        }\n      }\n      slots {\n        edges {\n          node {\n            id\n            startsAt\n            endsAt\n            participations {\n              edges {\n                node {\n                  id\n                  status\n                  images\n                  user {\n                    id\n                    name\n                    image\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query GetParticipation($id: ID!) {\n    participation(id: $id) {\n      id\n      images\n      reason\n      reservation {\n        id\n        opportunitySlot {\n          id\n          capacity\n          startsAt\n          endsAt\n          hostingStatus\n          opportunity {\n            id\n            title\n            description\n            body\n            category\n            capacity\n            pointsToEarn\n            feeRequired\n            requireApproval\n            publishStatus\n            image\n            files\n            createdAt\n            updatedAt\n            community {\n              id\n              name\n              image\n            }\n            createdByUser {\n              id\n              name\n              image\n            }\n            place {\n              id\n              name\n              address\n              latitude\n              longitude\n              city {\n                name\n                state {\n                  name\n                }\n              }\n            }\n            slots {\n              edges {\n                node {\n                  id\n                  startsAt\n                  endsAt\n                  participations {\n                    edges {\n                      node {\n                        id\n                        status\n                        images\n                        user {\n                          id\n                          name\n                          image\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n        participations {\n          id\n          user {\n            id\n            name\n            image\n          }\n        }\n      }\n      source\n      status\n      statusHistories {\n        edges {\n          node {\n            id\n            status\n            reason\n            createdAt\n            createdByUser {\n              id\n              name\n            }\n          }\n        }\n      }\n      updatedAt\n      user {\n        id\n        name\n        image\n      }\n    }\n  }\n",
): (typeof documents)["\n  query GetParticipation($id: ID!) {\n    participation(id: $id) {\n      id\n      images\n      reason\n      reservation {\n        id\n        opportunitySlot {\n          id\n          capacity\n          startsAt\n          endsAt\n          hostingStatus\n          opportunity {\n            id\n            title\n            description\n            body\n            category\n            capacity\n            pointsToEarn\n            feeRequired\n            requireApproval\n            publishStatus\n            image\n            files\n            createdAt\n            updatedAt\n            community {\n              id\n              name\n              image\n            }\n            createdByUser {\n              id\n              name\n              image\n            }\n            place {\n              id\n              name\n              address\n              latitude\n              longitude\n              city {\n                name\n                state {\n                  name\n                }\n              }\n            }\n            slots {\n              edges {\n                node {\n                  id\n                  startsAt\n                  endsAt\n                  participations {\n                    edges {\n                      node {\n                        id\n                        status\n                        images\n                        user {\n                          id\n                          name\n                          image\n                        }\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n        participations {\n          id\n          user {\n            id\n            name\n            image\n          }\n        }\n      }\n      source\n      status\n      statusHistories {\n        edges {\n          node {\n            id\n            status\n            reason\n            createdAt\n            createdByUser {\n              id\n              name\n            }\n          }\n        }\n      }\n      updatedAt\n      user {\n        id\n        name\n        image\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query SearchOpportunities(\n    $filter: OpportunityFilterInput\n    $first: Int\n  ) {\n    opportunities(\n      filter: $filter\n      first: $first\n    ) {\n      edges {\n        node {\n          id\n          title\n          description\n          category\n          capacity\n          community {\n            id\n            name\n            image\n          }\n          pointsToEarn\n          feeRequired\n          requireApproval\n          publishStatus\n          image\n          createdAt\n          updatedAt\n          place {\n            id\n            name\n            address\n            latitude\n            longitude\n            city {\n              name\n              state {\n                name\n              }\n            }\n          }\n          slots {\n            edges {\n              node {\n                id\n                startsAt\n                endsAt\n                capacity\n                participations {\n                  edges {\n                    node {\n                      id\n                      status\n                      user {\n                        id\n                        name\n                        image\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n",
): (typeof documents)["\n  query SearchOpportunities(\n    $filter: OpportunityFilterInput\n    $first: Int\n  ) {\n    opportunities(\n      filter: $filter\n      first: $first\n    ) {\n      edges {\n        node {\n          id\n          title\n          description\n          category\n          capacity\n          community {\n            id\n            name\n            image\n          }\n          pointsToEarn\n          feeRequired\n          requireApproval\n          publishStatus\n          image\n          createdAt\n          updatedAt\n          place {\n            id\n            name\n            address\n            latitude\n            longitude\n            city {\n              name\n              state {\n                name\n              }\n            }\n          }\n          slots {\n            edges {\n              node {\n                id\n                startsAt\n                endsAt\n                capacity\n                participations {\n                  edges {\n                    node {\n                      id\n                      status\n                      user {\n                        id\n                        name\n                        image\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: "\n  query GetUserWithDetailsAndPortfolios(\n    $id: ID!,\n    $first: Int,\n    $after: String,\n    $filter: PortfolioFilterInput,\n    $sort: PortfolioSortInput\n  ) {\n    user(id: $id) {\n      id\n      name\n      image\n      bio\n      sysRole\n      currentPrefecture\n      urlFacebook\n      urlInstagram\n      urlWebsite\n      urlX\n      urlYoutube\n      portfolios(\n        first: $first,\n        cursor: $after,\n        filter: $filter,\n        sort: $sort\n      ) {\n        edges {\n          node {\n            id\n            title\n            category\n            date\n            thumbnailUrl\n            source\n            place {\n              id\n              name\n            }\n            participants {\n              id\n              name\n              image\n            }\n          }\n          cursor\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n",
): (typeof documents)["\n  query GetUserWithDetailsAndPortfolios(\n    $id: ID!,\n    $first: Int,\n    $after: String,\n    $filter: PortfolioFilterInput,\n    $sort: PortfolioSortInput\n  ) {\n    user(id: $id) {\n      id\n      name\n      image\n      bio\n      sysRole\n      currentPrefecture\n      urlFacebook\n      urlInstagram\n      urlWebsite\n      urlX\n      urlYoutube\n      portfolios(\n        first: $first,\n        cursor: $after,\n        filter: $filter,\n        sort: $sort\n      ) {\n        edges {\n          node {\n            id\n            title\n            category\n            date\n            thumbnailUrl\n            source\n            place {\n              id\n              name\n            }\n            participants {\n              id\n              name\n              image\n            }\n          }\n          cursor\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;
