FROM node:20

ARG NEXT_PUBLIC_COMMUNITY_ID
ARG NEXT_PUBLIC_LIFF_ID
ARG NEXT_PUBLIC_LINE_CLIENT
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_DOMAIN
ARG NEXT_PUBLIC_API_ENDPOINT
ARG NEXT_PUBLIC_LIFF_LOGIN_ENDPOINT
ARG NEXT_PUBLIC_FIREBASE_AUTH_TENANT_ID
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_ACTIVITY_ADVANCE_BOOKING_DAYS_CONFIG

# NOTE: NEXT_PUBLIC_ 変数は、Next.jsビルド時に組み込まれるため、.envファイルを作って参照する必要がある
RUN touch .env
RUN echo "NEXT_PUBLIC_COMMUNITY_ID=$NEXT_PUBLIC_COMMUNITY_ID" >> .env
RUN echo "NEXT_PUBLIC_LIFF_ID=$NEXT_PUBLIC_LIFF_ID" >> .env
RUN echo "NEXT_PUBLIC_LINE_CLIENT=$NEXT_PUBLIC_LINE_CLIENT" >> .env
RUN echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID" >> .env
RUN echo "NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY" >> .env
RUN echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" >> .env
RUN echo "NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID" >> .env
RUN echo "NEXT_PUBLIC_DOMAIN=$NEXT_PUBLIC_DOMAIN" >> .env
RUN echo "NEXT_PUBLIC_API_ENDPOINT=$NEXT_PUBLIC_API_ENDPOINT" >> .env
RUN echo "NEXT_PUBLIC_LIFF_LOGIN_ENDPOINT=$NEXT_PUBLIC_LIFF_LOGIN_ENDPOINT" >> .env
RUN echo "NEXT_PUBLIC_FIREBASE_AUTH_TENANT_ID=$NEXT_PUBLIC_FIREBASE_AUTH_TENANT_ID" >> .env
RUN echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY" >> .env
# JSONデータを正しく.envファイルに書き込む
RUN printf 'NEXT_PUBLIC_ACTIVITY_ADVANCE_BOOKING_DAYS_CONFIG=%s\n' "$NEXT_PUBLIC_ACTIVITY_ADVANCE_BOOKING_DAYS_CONFIG" >> .env

# グローバルに pnpm をインストール
RUN npm install -g pnpm

# アプリケーションディレクトリを作成
WORKDIR /app

# 依存関係の定義ファイルを先にコピー (キャッシュのため)
COPY package.json pnpm-lock.yaml ./
COPY patches/ ./patches/

# 依存関係をインストール
RUN pnpm install

# 残りのソースコードをコピー
COPY . ./

# ビルド
RUN pnpm build

# アプリケーション起動
CMD ["pnpm", "start"]
