name: Build and Deploy (Prd)

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Build & Deploy
    uses: ./.github/workflows/_deploy-cloud-run.yml
    secrets: inherit
    with:
      environment: co-creation-dao-prod
      app_env_build_arg: ""
      runtime_env_vars: |
        NODE_ENV=production
      image_tag: ${{ github.sha }}
